### ISSUE TITLE
Tests not successful on Travis

### ISSUE THREAD

**Issue by 153957** [leukeleu/wagtail_lightadmin#1]
I have mostly fixed the tests on Travis CI.
However, there still seems to be an issue with the version of sqlite3, maybe that can also be updated on Travis, or use postgres instead.

**Comment by c-herrewijn** [comment]
fixed in commits:
6c94dd18a99f331a56b28095fe1499618e75a2c1
8b0123f4ecbee7a13ba3d01a47f5df6eb56a08d0
